### ISSUE TITLE
Honeybee can't find the installation folder for custom installation folder structure

### ISSUE THREAD

**Issue by MadsPJ** [ladybug-tools/honeybee-dynamo#42] opened 2017-03-07 14:54 UTC
Hello,

I have a problem getting Honeybee and Ladybug to run. I installed both packages through the package manager. I looked through old videos and it seems like previously you had to first install the package and then install it inside Dynamo. In this version everything seems to be installed after the package, but it I keep getting the error:  "'Honeybee is not installed! Install it from package manager". What am I doing wrong?

**Comment by mostaphaRoudsari** [comment] 2017-03-07 15:21
@MadsPJ Your assumptions are right. what is the error message?

**Comment by MadsPJ** [comment] 2017-03-07 15:49
Hello Mostapha,

I get the following error:

"List:
0 null
ERROR:
Honeybee is not installed! Install it from package manager

If you thinks this is a bug submist an issue on github (...) and include below error message:
1 Traceback (most recent call last):
File "<string>", line 49, in <module>
ImportError: Honeybee is not installed! Install it from package manager."

**Comment by mostaphaRoudsari** [comment] 2017-03-07 16:07
Thanks. I will check and get back to you later today. I haven't made any changes to the installation. It's strange that you get an error like this.

**Comment by MadsPJ** [comment] 2017-03-09 08:49
Im using Dynamo version 1.2.1.3083. I dont know if that has any influence. 

I have reinstalled the packeges but i still get the same error.

**Comment by teabaker** [comment] 2017-03-09 13:47
I experience the same problem, also with Ladybug components. For me it is an intermittant problem that I can only solve by restarting both Revit and Dynamo.

**Comment by mostaphaRoudsari** [comment] 2017-03-09 13:54
I will check this today and report back. I couldn't reproduce the error.

**Comment by schaggar16** [comment] 2017-03-10 08:27
i had the same issue but did find a workaround. by creating the following folder structure and placing a copy of the DynamoSettings.xml here. Has done the trick so far. 
C:\Users\User\AppData\Roaming\Dynamo 1.2\Dynamo Revit\1.2

**Comment by MadsPJ** [comment] 2017-03-10 09:04
Thanks for the input.

However Dynamosettings.xml was placed in that folder by default on my computer and it allways occours even after reinstalling and after Revit and Dynamo is opened and closed.

**Comment by schaggar16** [comment] 2017-03-10 09:46
That is very interesting. By default my dynamo installation creates: 
C:\Users\User\AppData\Roaming\Dynamo\Dynamo Revit\1.2 which contains the 'Live' DynamoSettings.xml and then i have my 'copied' version sitting here: 
C:\Users\User\AppData\Roaming\Dynamo 1.2\Dynamo Revit\1.2

**Comment by MadsPJ** [comment] 2017-03-10 13:19
No you are right! As a default I have it the same place as you. My bad.

I didnt have the Dynamo 1.2\Dynamo Revit\1.2 folders and created those, but i still get the same error. 

My Dynamo is not installed under the default user but my usename. I tried to create new folders to make a similar filepath but it didn't work.

**Comment by mostaphaRoudsari** [comment] 2017-03-10 13:33
That should not happen. Honeybee looks for the xml file under `c:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\1.2`. Let's see if we can figure out why is it happening. Can you open one of the dyf files and copy the first two nodes in a definition and see what is the error message?

![image](https://cloud.githubusercontent.com/assets/2915573/23797095/2f435efc-056c-11e7-9678-3e1627646b0a.png)


![image](https://cloud.githubusercontent.com/assets/2915573/23797020/d8723076-056b-11e7-8787-08196b34fb33.png)

This should help us to understand what is going wrong.

**Comment by MadsPJ** [comment] 2017-03-10 14:07
I get the same error message:

![error](https://cloud.githubusercontent.com/assets/26253323/23798080/2a525312-05a3-11e7-802e-0ce32845e5bc.JPG)

**Comment by mostaphaRoudsari** [comment] 2017-03-10 14:28
Thanks! Can you try this file? [check installation folders.zip](https://github.com/ladybug-tools/honeybee-plus/files/834172/check.installation.folders.zip)

![image](https://cloud.githubusercontent.com/assets/2915573/23798624/7cbc15a0-0573-11e7-9382-0bd3b485953a.png)

This should give a list for paths that honeybee is looking to find the XML file and then the path for packages. Let's check if it looks into the correct folders in the first place.

**Comment by MadsPJ** [comment] 2017-03-10 14:57
Yes off course. Thank for the help:

![error2](https://cloud.githubusercontent.com/assets/26253323/23799821/36eb57a2-05aa-11e7-89aa-900a9c2bb65d.JPG)

**Comment by mostaphaRoudsari** [comment] 2017-03-10 15:05
Hmm... There are several package folders in your case. Now let's see why it can't find honeybee. The code looks under each of the folders to find `[folder]\packages\honeybee\extra`.

What is the full path to your Honeybee installation folder? Is that follow the same structure?

**Comment by MadsPJ** [comment] 2017-03-10 15:28
apparently my ful path was:
C:\Users\mpj\Documents\SJ nodes\Honeybee
Which was my default save location.

I then manually copied  Honeybee into the following folder:
C:\Users\mpj\AppData\Roaming\Dynamo\Dynamo Revit\1.2\packages\Honeybee

And then its working! Great! thanks Mosapha! Now I have a new toy to play with in the weekend

**Comment by mostaphaRoudsari** [comment] 2017-03-10 15:30
Perfect! Happy that it's finally solved.
I keep this issue open to make the searching function for flexible for cases such as yours.

**Comment by schaggar16** [comment] 2017-05-16 16:19
@mostaphaRoudsari one of my colleagues was having this issue - i ran the code snippet you had above to check the folder path for packages but it didnt show anything. Just showed the location of the .XML files but nothing uner package folders. Any ideas?

**Comment by mostaphaRoudsari** [comment] 2017-05-27 21:26
@schaggar16 is Honeybee installed under one of the folders inside `packages` folder?

**Comment by schaggar16** [comment] 2017-05-27 22:09
@mostaphaRoudsari - we found the issue was that the location of the .xml returned by your script was different to where it actually was. Your code is fine, its the installation of dynamo which is the source of the problem for us. A temp work around is to create the location of the xml. based on your code snippet but will be investigating further into the dynamo installation method. 
Thanks for your help.

**Comment by mostaphaRoudsari** [comment] 2017-05-28 20:37
Hi @schaggar16, Thanks for the update. I would open an issue for this on Dynamo's repository. The sooner they get it fixed the better.

**Closed** 2017-07-23 23:30 UTC
Labels: bug, critical, dynamo

**Comment by nuyaan** [comment] 2019-02-09 15:52
Hi @mostaphaRoudsari
Im using Dynamo version 2.0.2 
I have installed the packeges but i still get the same error.
